FROM homeassistant/home-assistant:2023.4

#RUN sed -i "s/after_dependencies.*/after_dependencies\"\: \[\"bluerpc\", \"esphome\", \"shelly\", \"ruuvi_gateway\"\],/" /usr/src/homeassistant/homeassistant/components/bluetooth_adapters/manifest.json
ADD manifest.json /usr/src/homeassistant/homeassistant/components/bluetooth_adapters/manifest.json
